#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : valijson
Version  : 1.0.1
Release  : 2
URL      : https://github.com/tristanpenman/valijson/archive/v1.0.1/valijson-1.0.1.tar.gz
Source0  : https://github.com/tristanpenman/valijson/archive/v1.0.1/valijson-1.0.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: valijson-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : pkg-config
BuildRequires : qtbase-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
CMake modules copied from:
https://github.com/sourcey/libsourcey

%package dev
Summary: dev components for the valijson package.
Group: Development
Provides: valijson-devel = %{version}-%{release}
Requires: valijson = %{version}-%{release}

%description dev
dev components for the valijson package.


%package license
Summary: license components for the valijson package.
Group: Default

%description license
license components for the valijson package.


%prep
%setup -q -n valijson-1.0.1
cd %{_builddir}/valijson-1.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1695773997
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1695773997
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/valijson
cp %{_builddir}/valijson-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/valijson/20c2586c26d01d1b0a233252f957127d0218da7d || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/compat/optional.hpp
/usr/include/valijson/adapters/boost_json_adapter.hpp
/usr/include/valijson/adapters/json11_adapter.hpp
/usr/include/valijson/adapters/jsoncpp_adapter.hpp
/usr/include/valijson/adapters/nlohmann_json_adapter.hpp
/usr/include/valijson/adapters/picojson_adapter.hpp
/usr/include/valijson/adapters/poco_json_adapter.hpp
/usr/include/valijson/adapters/property_tree_adapter.hpp
/usr/include/valijson/adapters/qtjson_adapter.hpp
/usr/include/valijson/adapters/rapidjson_adapter.hpp
/usr/include/valijson/adapters/std_string_adapter.hpp
/usr/include/valijson/adapters/yaml_cpp_adapter.hpp
/usr/include/valijson/constraint_builder.hpp
/usr/include/valijson/constraints/basic_constraint.hpp
/usr/include/valijson/constraints/concrete_constraints.hpp
/usr/include/valijson/constraints/constraint.hpp
/usr/include/valijson/constraints/constraint_visitor.hpp
/usr/include/valijson/exceptions.hpp
/usr/include/valijson/internal/adapter.hpp
/usr/include/valijson/internal/basic_adapter.hpp
/usr/include/valijson/internal/custom_allocator.hpp
/usr/include/valijson/internal/debug.hpp
/usr/include/valijson/internal/frozen_value.hpp
/usr/include/valijson/internal/json_pointer.hpp
/usr/include/valijson/internal/json_reference.hpp
/usr/include/valijson/internal/optional.hpp
/usr/include/valijson/internal/optional_bundled.hpp
/usr/include/valijson/internal/uri.hpp
/usr/include/valijson/schema.hpp
/usr/include/valijson/schema_parser.hpp
/usr/include/valijson/subschema.hpp
/usr/include/valijson/utils/boost_json_utils.hpp
/usr/include/valijson/utils/file_utils.hpp
/usr/include/valijson/utils/json11_utils.hpp
/usr/include/valijson/utils/jsoncpp_utils.hpp
/usr/include/valijson/utils/nlohmann_json_utils.hpp
/usr/include/valijson/utils/picojson_utils.hpp
/usr/include/valijson/utils/poco_json_utils.hpp
/usr/include/valijson/utils/property_tree_utils.hpp
/usr/include/valijson/utils/qtjson_utils.hpp
/usr/include/valijson/utils/rapidjson_utils.hpp
/usr/include/valijson/utils/utf8_utils.hpp
/usr/include/valijson/utils/yaml_cpp_utils.hpp
/usr/include/valijson/validation_results.hpp
/usr/include/valijson/validation_visitor.hpp
/usr/include/valijson/validator.hpp
/usr/lib64/cmake/valijson/valijsonConfig.cmake

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/valijson/20c2586c26d01d1b0a233252f957127d0218da7d
